In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
b=np.array([(1.2,2,3),(4,5,6)],dtype=float)

In [4]:
c=np.array([[(1.2,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [7]:
e=np.linspace(0,2,9)

In [8]:
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [10]:
x=np.eye(3)

In [11]:
y=np.random.random((2,2))

In [12]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
y

array([[0.7838788 , 0.19667378],
       [0.26449624, 0.50511557]])

In [14]:
np.shape(a)

(3,)

In [15]:
np.shape(b)

(2, 3)

In [16]:
np.shape(c)

(2, 2, 3)

In [17]:
np.ndim(a)

1

In [18]:
np.ndim(b)

2

In [19]:
np.ndim(c)

3

In [20]:
np.size(a)

3

In [21]:
np.size(b)

6

In [22]:
np.size(c)

12

In [23]:
a.dtype

dtype('int32')

In [24]:
b.dtype

dtype('float64')

In [25]:
c.dtype

dtype('float64')

In [26]:
a.dtype.name

'int32'

In [27]:
b.dtype.name

'float64'

In [28]:
c.dtype.name

'float64'

In [29]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
x=np.multiply(b,b)

In [31]:
x

array([[ 1.44,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [32]:
np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.add(a,b)

array([[2.2, 4. , 6. ],
       [5. , 7. , 9. ]])

In [34]:
np.subtract(a,b)

array([[-0.2,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [35]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [36]:
np.sqrt(b)

array([[1.09544512, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
np.sqrt(c)

array([[[1.09544512, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [38]:
np.add(a,b)

array([[2.2, 4. , 6. ],
       [5. , 7. , 9. ]])

In [39]:
np.min(a)

np.int32(1)

In [40]:
np.int32(1)

np.int32(1)

In [41]:
np.max(a)

np.int32(3)

In [42]:
np.cumsum(a)

array([1, 3, 6])

In [43]:
np.mean(a)

np.float64(2.0)

In [44]:
np.median(a)

np.float64(2.0)

In [45]:
np.std(a)

np.float64(0.816496580927726)